name: MASSLearning
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - hypothesis=3.82.1
  - ipython=7.1.1
  - matplotlib=3.1.0
  - pandas=0.23.4
  - python=3.6.6
  - pytorch=1.0.0
  - scikit-learn=0.20.2
  - scipy=1.2.0
  - seaborn=0.9.0
  - torchvision=0.2.1
  - pip:
      - tensorboardx==1.4

